### ISSUE TITLE
mc doesn't render correctly

### ISSUE THREAD

**Issue by plfiorini** [rburchell/literm_old#15]
![screenshot from 2017-04-18 19-53-39](https://cloud.githubusercontent.com/assets/843710/25145203/c8f09b8c-2470-11e7-9812-c2f05f71fcfd.png)

Log:
[log_mc.txt](https://github.com/rburchell/literm/files/930606/log_mc.txt)

**Comment by rburchell** [comment]
Interestingly, this looks like it might be Linux-specific. Here's a Mac screenshot for comparison:
<img width="865" alt="screen shot 2017-04-18 at 20 07 59" src="https://cloud.githubusercontent.com/assets/125863/25146055/e1c87362-2472-11e7-8ead-3ab181f28a90.png">

There's clearly some problems for me too (BCE, #1) -- but it's nowhere near that weird.

**Comment by rburchell** [comment]
6ce0e5fea7d082a5e5c217235f4af2865ed7ca25 helps this for me a lot.

**Comment by rburchell** [comment]
Side by side comparison:

![Linux](https://cloud.githubusercontent.com/assets/125863/25151024/4dfb2b7c-2484-11e7-806e-d47bbe1d72d4.png)
![Mac](https://cloud.githubusercontent.com/assets/125863/25151033/54ea7212-2484-11e7-9dc5-a43e3cd7e50f.png)

**Comment by plfiorini** [comment]
Works fine here (Linux) with `monospace` but it doesn't with `Droid Sans Mono`.

**Comment by rburchell** [comment]
The original issue is now fixed. Let's move the font-specific issues to a new bug. I "can't wait" to find out what's up there. :-)
