### ISSUE TITLE
Bad mc rendering with some fonts

### ISSUE THREAD

**Issue by plfiorini** [rburchell/literm_old#19]
On Linux it works fine with Liberation Mono:

![screenshot from 2017-04-18 22-46-05](https://cloud.githubusercontent.com/assets/843710/25152344/ebbc0ab2-2488-11e7-98a6-0280ecf02cef.png)

and the default for monospace, but it's not for Droid Sans Mono:

![screenshot from 2017-04-18 22-47-51](https://cloud.githubusercontent.com/assets/843710/25152382/11e5848e-2489-11e7-99f5-d94cbf377e51.png)

and Noto Mono:

![screenshot from 2017-04-18 22-48-37](https://cloud.githubusercontent.com/assets/843710/25152418/31af76a8-2489-11e7-8af8-0edbd195e2cb.png)

and Oxygen Mono:

![screenshot from 2017-04-18 22-49-21](https://cloud.githubusercontent.com/assets/843710/25152459/4a82d51c-2489-11e7-837f-ae69babe043a.png)

**Comment by rburchell** [comment]
So long as there's at least one working font, I consider this lower priority right now, but it should be fixed. Anyone who wants to look into it is welcome.

**Comment by rburchell** [comment]
Can you please try this? I'm not sure why it helps, but it appears to, perhaps it gives you an idea?

```
diff --git a/qml/Yat/plugin/mono_text.cpp b/qml/Yat/plugin/mono_text.cpp
index faec0c1..6b47d25 100644
--- a/qml/Yat/plugin/mono_text.cpp
+++ b/qml/Yat/plugin/mono_text.cpp
@@ -97,6 +97,8 @@ public:
 
     void setUnicodeText(const QString &text, const QFont &font, const QColor &color)
     {
+setLatinText(text,font,color);
+return;
         deleteContent();
         QRawFont raw_font = QRawFont::fromFont(font, QFontDatabase::Latin);
         qreal line_width = raw_font.averageCharWidth() * text.size();
```
