### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by rburchell** [rburchell/literm_old#20]
I think we may need to drop the Mac builds. They take a very long time, probably due to limited hardware from Travis.

It would also be interesting to look into coveralls.io (& https://github.com/eddyxu/cpp-coveralls) for code coverage reports. We have a lot of untested code at the moment, but I'd like to improve that over time.

**Comment by rburchell** [comment]
@plfiorini, any chance you have interest in helping with this?

**Comment by plfiorini** [comment]
Sure

**Comment by plfiorini** [comment]
@rburchell clazy sounds like a good addition to the CI, maybe I can hack something that build it once and cache the binaries because it takes a long time to build

**Comment by rburchell** [comment]
Going to consider this finished with b9431e7970c1b6b7c5c0eaab3cd314355dca5f82. I took a look at coveralls and a few alternatives, but they look a little too full of magic and wizardry for me to be too comfortable with for now.
